name: CI

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  clj:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Prepare java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '11'

    - name: Install clojure tools
      uses: DeLaGuardo/setup-clojure@12.5
      with:
        cli: latest

    - name: Cache clojure dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.m2/repository
          ~/.gitlibs
          ~/.deps.clj
        key: cljdeps-${{ hashFiles('deps.edn') }}
        restore-keys: cljdeps-

    - name: Run lint
      run: clojure -M:lint

    - name: Run tests
      run: clojure -M:test

    - name: Build uberjar
      run: clojure -T:build uber